### ISSUE TITLE
Run completely offline from a folder?

### ISSUE THREAD

**Issue by poVoq** [rainu/dev-notes#32]
Maybe I am overlooking something, but it it possible to run with app without a NodeJS server?

Basically  would like to download it and run the (non-existing) index.html from a folder.

Thanks in advance for clarifying this :)

**Comment by rainu** [comment]
Because this is a progressive web app (pwa) you need a webserver (such like nodejs) to deliver this content to the user. 
But if you want to "install" it on your Desktop-PC  or Mobilephone you have to open the link https://rainu.github.io/dev-notes/ with Chrome-Browser (for the moment it works only there). The chrome-browser sees that this is a pwa and you can install this application. In Desktop-Mode you can click the "plus"-icon in the right corner inside the url-bar. 
If you open this url in a chrome at a smartphone you should get a promt which asks you if you want to install this application.

**Comment by poVoq** [comment]
Hmm, maybe I don't properly understand the concept of PWAs, but shouldn't there be a way to deliver it in a different way on platforms that do not support PWA?
Seems strange that the only way to make a offline PWA work is by distributing it though a server.

But you can close this if it is really not possible.

Background: I was thinking of wrapping this up as a webapp for Ubuntu Touch. PWA directly isn't supported (yet) on this platform, but it is really easy to make webapps in a non-PWA way.

**Comment by rainu** [comment]
Ok im not familiar with Ubuntu Touch. But if i understand it correctly you just want the access to the html/css/js files. May you have a look at [docs folder](https://github.com/rainu/dev-notes/tree/master/docs). Inside this folder there are all pre-compiled assets (thats 1:1 the content which should be delivered by a server) ... I use the doc-folder to deploy this application at the github-pages. So the links are hardcoded to "/dev-notes/" (cause github pages needs that). If you need a other url-prefix you can check this project out and build it for your own:
* Edit the file [package.json - Line 10](https://github.com/rainu/dev-notes/blob/master/package.json#L10) and remove "DEPLOY_ENV=GH_PAGES"
* trigger the build: npm run generate
* after that you will find the whole assets in your local "docs"-directory

**Comment by poVoq** [comment]
Oh, I overlooked that. Yes that might work. Thanks a lot!

**Comment by poVoq** [comment]
Removing "DEPLOY_ENV=GH_PAGES" just resulted in an ever spinning circle on white background.

Recompiling it with the absolute file path substituted for /dev-notes/ kind of worked, at least I got to a broken version of dev-notes. Same behaviour on my Linux desktop with an absolute file path.
I get the top-bar the the info modal works, but on the main view it just says "404 not found" and if I try for example the settings menu I get thrown back to a file explorer in my browser.

I guess this is way out of your target with this project, but maybe you have a good idea what else to try?

Just connecting to https://rainu.github.io/dev-notes/ works fine by the way on the embedded webview browser that comes with Ubuntu Touch, so the app itself should work. It's just to get it to run offline without PWA.

**Comment by rainu** [comment]
> Removing "DEPLOY_ENV=GH_PAGES" just resulted in an ever spinning circle on white background.
I only seen this before if there is no support for [indexdb](https://github.com/rainu/dev-notes/blob/master/store/localStore.js#L27). (You should seen that also if you use the "private mode" from firefox or similar browsers). I was to lazy to build a view for that case ;) But you should see it in the console: "No available storage method found."
So if you dont have indexedDB available there is no way to use this application because i store all data in there. Maybe I can implements a alternative for indexedDB or I can found a easy solution in localForage (the lib i used as abstraction layer). But at the moment it is not my highest priority :) Or maybe you can have a look and open an PullRequest ;)

**Comment by rainu** [comment]
Oh! I have seen that I forced to use the indexedDB ... but localforage provides a mechanism to choose a right driver by its own. So i will try to remove my forcing. After that you can try it again ;)

**Comment by rainu** [comment]
Yeah! It was that easy ;) So you can try it again and have a nice x-mas :)
